"""Pixelle release protocol patch for ComfyUI-OmniVoice.

This script patches the ComfyUI-OmniVoice plugin to expose Pixelle-compatible
release endpoints that clear PyTorch model caches not managed by ComfyUI's
standard model manager.

Usage:
    python tools/patch_omnivoice_plugin.py --target /path/to/ComfyUI-OmniVoice
    # Or with environment variable:
    OMNIVOICE_PLUGIN_DIR=/path/to/ComfyUI-OmniVoice python tools/patch_omnivoice_plugin.py

After patching, restart ComfyUI for the endpoints to take effect:
    - GET /pixelle/omnivoice/health
    - POST /pixelle/omnivoice/free
"""

import argparse
import gc
import os
import sys
from dataclasses import dataclass
from pathlib import Path

OMNIVOICE_PLUGIN_ENV = "OMNIVOICE_PLUGIN_DIR"
PLUGIN_INIT_RELATIVE_PATH = Path("__init__.py")
PIXELLE_ROUTES_RELATIVE_PATH = Path("pixelle_routes.py")

# Known OmniVoice node class names from workflows
OMNIVOICE_NODE_CLASSES = (
    "OmniVoiceLongformTTS",
    "OmniVoiceVoiceCloneTTS",
)


@dataclass(frozen=True)
class PatchResult:
    changed_files: list[Path]


def resolve_target_path(target_arg: str | os.PathLike[str] | None) -> Path:
    if target_arg:
        return Path(target_arg)

    target_env = os.environ.get(OMNIVOICE_PLUGIN_ENV)
    if target_env:
        return Path(target_env)

    raise ValueError(f"Pass --target or set {OMNIVOICE_PLUGIN_ENV} to the ComfyUI-OmniVoice directory")


def patch_plugin(target: str | os.PathLike[str]) -> PatchResult:
    plugin_dir = Path(target)
    if not plugin_dir.exists():
        raise FileNotFoundError(f"target plugin directory does not exist: {plugin_dir}")
    if not plugin_dir.is_dir():
        raise NotADirectoryError(f"target plugin path is not a directory: {plugin_dir}")

    plugin_init_path = plugin_dir / PLUGIN_INIT_RELATIVE_PATH
    routes_path = plugin_dir / PIXELLE_ROUTES_RELATIVE_PATH
    _require_file(plugin_init_path, PLUGIN_INIT_RELATIVE_PATH)

    changed_files: list[Path] = []
    if _patch_file(plugin_init_path, _patch_plugin_init):
        changed_files.append(plugin_init_path)
    if _write_stable_file(routes_path, STABLE_PIXELLE_OMNIVOICE_ROUTES):
        changed_files.append(routes_path)
    return PatchResult(changed_files=changed_files)


def _require_file(path: Path, relative_path: Path) -> None:
    display_path = relative_path.as_posix()
    if not path.exists():
        raise FileNotFoundError(f"required plugin file is missing: {display_path}")
    if not path.is_file():
        raise FileNotFoundError(f"required plugin path is not a file: {display_path}")


def _patch_file(path: Path, patcher) -> bool:
    original = path.read_text(encoding="utf-8")
    patched = patcher(original)
    if patched == original:
        return False
    path.write_text(patched, encoding="utf-8")
    return True


def _write_stable_file(path: Path, content: str) -> bool:
    original = path.read_text(encoding="utf-8") if path.exists() else None
    if original == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def _patch_plugin_init(text: str) -> str:
    import_line = "from . import pixelle_routes as _pixelle_routes"
    if import_line in text:
        return text

    lines = text.splitlines()
    insert_at = 0
    if lines and lines[0].startswith('"""'):
        insert_at = 1
        while insert_at < len(lines) and not lines[insert_at].endswith('"""'):
            insert_at += 1
        insert_at = min(insert_at + 1, len(lines))

    while insert_at < len(lines) and (
        lines[insert_at].startswith("import ")
        or lines[insert_at].startswith("from ")
        or not lines[insert_at].strip()
    ):
        insert_at += 1

    lines.insert(insert_at, import_line)
    return "\n".join(lines) + ("\n" if text.endswith("\n") else "")


STABLE_PIXELLE_OMNIVOICE_ROUTES = '''"""Pixelle release protocol endpoints for ComfyUI-OmniVoice.

This module is auto-generated by tools/patch_omnivoice_plugin.py.
Do not edit manually; run the patch script again to regenerate.
"""

import gc
import sys

import torch
from aiohttp import web
from server import PromptServer

_PIXELLE_OMNIVOICE_RELEASE_CONTRACT_REVISION = 1

# Known OmniVoice node class names
_OMNIVOICE_NODE_CLASSES = (
    "OmniVoiceLongformTTS",
    "OmniVoiceVoiceCloneTTS",
)


def _cuda_snapshot() -> dict:
    if not torch.cuda.is_available():
        return {}
    device = torch.cuda.current_device()
    return {
        "cuda_allocated": int(torch.cuda.memory_allocated(device)),
        "cuda_reserved": int(torch.cuda.memory_reserved(device)),
    }


def _find_omnivoice_node_classes() -> dict[str, type]:
    """Find OmniVoice node classes in loaded modules."""
    classes = {}
    for module_name, module in list(sys.modules.items()):
        if module is None:
            continue
        # Check for OmniVoice node classes in the module
        for class_name in _OMNIVOICE_NODE_CLASSES:
            if hasattr(module, class_name):
                cls = getattr(module, class_name)
                if isinstance(cls, type):
                    classes[f"{module_name}.{class_name}"] = cls
    return classes


def _find_omnivoice_objects() -> list[str]:
    """Find OmniVoice model objects in memory."""
    labels = []
    
    # Find node class instances
    node_classes = _find_omnivoice_node_classes()
    for full_name, cls in node_classes.items():
        for obj in gc.get_objects():
            try:
                if isinstance(obj, cls):
                    labels.append(full_name)
                    break
            except Exception:
                continue
    
    # Look for module-level caches and model references
    for module_name in list(sys.modules.keys()):
        if "omnivoice" not in module_name.lower() and "omni_voice" not in module_name.lower():
            continue
        module = sys.modules.get(module_name)
        if module is None:
            continue
        # Check for common model attributes
        for attr_name in ["_model", "model", "tts_model", "omnivoice", "pipe", "_omnivoice"]:
            if hasattr(module, attr_name):
                obj = getattr(module, attr_name)
                if obj is not None:
                    labels.append(f"{module_name}.{attr_name}")
        # Check for model cache dictionaries
        for cache_name in ["_cache", "_models", "_model_cache", "MODEL_CACHE", "_instances"]:
            cache = getattr(module, cache_name, None)
            if isinstance(cache, dict) and cache:
                for key in cache.keys():
                    labels.append(f"{module_name}.{cache_name}[{key}]")
    
    return sorted(set(labels))


_MIN_CUDA_ALLOCATED_RELEASE_BYTES = 64 * 1024 * 1024
_MIN_CUDA_ALLOCATED_RELEASE_RATIO = 0.05


def _cuda_allocated_release_is_material(before_bytes: int, after_bytes: int) -> bool:
    if before_bytes <= 0 or after_bytes >= before_bytes:
        return False
    release_bytes = before_bytes - after_bytes
    relative_threshold = max(1, int(before_bytes * _MIN_CUDA_ALLOCATED_RELEASE_RATIO))
    threshold = min(_MIN_CUDA_ALLOCATED_RELEASE_BYTES, relative_threshold)
    return release_bytes >= threshold


def omnivoice_release_health() -> dict:
    objects_seen = _find_omnivoice_objects()
    snapshot = _cuda_snapshot()
    return {
        "protocol_version": 2,
        "contract_revision": _PIXELLE_OMNIVOICE_RELEASE_CONTRACT_REVISION,
        "ok": True,
        "extension": "omnivoice",
        "release_endpoint": "/pixelle/omnivoice/free",
        "safe_to_continue": True,
        "objects_seen": objects_seen,
        "residual_objects": [],
        "errors": [],
        "cuda_allocated": snapshot.get("cuda_allocated", 0),
        "cuda_reserved": snapshot.get("cuda_reserved", 0),
    }


def unload_omnivoice_models() -> dict:
    """Release OmniVoice models from memory."""
    errors = []
    before = _cuda_snapshot()
    objects_seen = _find_omnivoice_objects()

    # Try to release OmniVoice-specific models
    try:
        # Clear any global model references in OmniVoice modules
        for module_name in list(sys.modules.keys()):
            if "omnivoice" not in module_name.lower() and "omni_voice" not in module_name.lower():
                continue
            module = sys.modules.get(module_name)
            if module is None:
                continue
            # Clear common model attributes
            for attr_name in ["_model", "model", "tts_model", "omnivoice", "pipe", "_omnivoice"]:
                if hasattr(module, attr_name):
                    try:
                        setattr(module, attr_name, None)
                    except Exception as exc:
                        errors.append(f"Failed to clear {module_name}.{attr_name}: {exc}")
            # Clear cache dictionaries
            for cache_name in ["_cache", "_models", "_model_cache", "MODEL_CACHE", "_instances"]:
                cache = getattr(module, cache_name, None)
                if isinstance(cache, dict):
                    try:
                        cache.clear()
                    except Exception as exc:
                        errors.append(f"Failed to clear {module_name}.{cache_name}: {exc}")
    except Exception as exc:
        errors.append(str(exc))

    # Standard ComfyUI cleanup
    try:
        import comfy.model_management
        comfy.model_management.unload_all_models()
        comfy.model_management.soft_empty_cache()
    except Exception as exc:
        errors.append(str(exc))

    # PyTorch garbage collection and cache clearing
    try:
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.synchronize()
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()
    except Exception as exc:
        errors.append(str(exc))

    diagnostic_objects = _find_omnivoice_objects()
    after = _cuda_snapshot()
    cuda_allocated_before = before.get("cuda_allocated", 0)
    cuda_allocated_after = after.get("cuda_allocated", 0)
    cuda_allocated_decreased = _cuda_allocated_release_is_material(
        cuda_allocated_before,
        cuda_allocated_after,
    )

    residual_objects = []
    release_confirmation_reason = "omnivoice_objects_released"
    if diagnostic_objects and not cuda_allocated_decreased:
        residual_objects = diagnostic_objects
        release_confirmation_reason = "omnivoice_objects_residual"
    elif errors:
        release_confirmation_reason = "omnivoice_release_errors"
    elif cuda_allocated_decreased:
        release_confirmation_reason = "omnivoice_cuda_allocated_decreased"

    safe_to_continue = not errors and not residual_objects

    return {
        "protocol_version": 2,
        "contract_revision": _PIXELLE_OMNIVOICE_RELEASE_CONTRACT_REVISION,
        "extension": "omnivoice",
        "released": bool(objects_seen) or cuda_allocated_decreased,
        "safe_to_continue": safe_to_continue,
        "release_confirmation_reason": release_confirmation_reason,
        "objects_seen": objects_seen,
        "objects_released": [item for item in objects_seen if item not in diagnostic_objects],
        "diagnostic_objects": diagnostic_objects,
        "residual_objects": residual_objects,
        "errors": errors,
        "cuda_allocated_before": cuda_allocated_before,
        "cuda_allocated_after": cuda_allocated_after,
        "cuda_reserved_before": before.get("cuda_reserved", 0),
        "cuda_reserved_after": after.get("cuda_reserved", 0),
    }


@PromptServer.instance.routes.get("/pixelle/omnivoice/health")
async def pixelle_health_omnivoice(request):
    return web.json_response(omnivoice_release_health())


@PromptServer.instance.routes.post("/pixelle/omnivoice/free")
async def pixelle_free_omnivoice(request):
    result = unload_omnivoice_models()
    status = 500 if result.get("errors") else 200
    return web.json_response(result, status=status)
'''


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Patch ComfyUI-OmniVoice with Pixelle release protocol endpoints.",
    )
    parser.add_argument(
        "--target",
        help=f"Path to ComfyUI-OmniVoice plugin directory. Defaults to ${OMNIVOICE_PLUGIN_ENV}.",
    )
    args = parser.parse_args(argv)

    target = resolve_target_path(args.target)
    result = patch_plugin(target)
    if result.changed_files:
        print("Patched files:")
        for path in result.changed_files:
            print(f"  - {path}")
    else:
        print("ComfyUI-OmniVoice Pixelle release patch already up to date.")
    print("Restart ComfyUI for the OmniVoice release endpoints to take effect.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
